#!/usr/bin/env bash

# Script Overview
#
# This Bash script provides functionality to manage Tmux sessions interactively
# using FZF (Fuzzy Finder).
#
# Usage
#
# The script can be executed with the following command line options:
#
# - `-a`: Create a new Tmux session based on the selected directory using `fd`
#   (alternative to `find`) and `fzf-tmux`.
# - `-n`: Create a new Tmux session based on the selected directory using
#   `zoxide` and `fzf-tmux`.
# - `-t`: Switch or attach to an existing Tmux session.
#
# Dependencies
#
# - Tmux: Terminal multiplexer.
# - FZF: Fuzzy Finder for command-line.
# - fd: Alternative to `find` command, used for directory selection.
# - zoxide: A smarter `cd` command that tracks your most used directories.
#
# Functionality
#
# Creating a New Tmux Session
#
# When using the `-a` or `-n` option, the script allows the user to select a
# directory interactively using FZF. It then creates a new Tmux session based on
# the selected directory, appending a timestamp to


FZF_DEFAULT_OPTS="
--height 50% -1 
--reverse
"
# --inline-info

function goto_or_kill_session() {
    FZF_TMUX_OPTIONS="
        --border-label='Tmux Sessions'
        --multi
        --exit-0
        --expect=ctrl-alt-k,ctrl-r,enter
        --header='enter=switch, C-M-k=kill, C-r=rename'
        --preview='tmux_pane_preview {} | bat --style plain'
        --preview-window='down,70%,border-rounded'
    "

    # Store current session window pane
    curr_session_window_pane=$(tmux display-message -p '#{session_name}:#{window_id}.#{pane_id}')

    # Get the names of all sessions
    sessions_list=$(tmux list-sessions -F '#{session_name}')

    # This variable stores the list of all available windows and panes from all sessions
    # except the current one. Each entry in the string follows the format:
    # <session name>:<window index>.<pane index>\n
    # For example:
    # foo/sub-foo:1.1
    # bar/sub-bar1:1.1
    # bar/sub-bar1:1.2
    # 
    # NOTE: I used #{window_index} and #{pane_index} instead of their IDs as it is more 
    # user-readable.
    # However, this brings some complications to kill-pane, which requires preprocessing before 
    # killing the panes: I need to convert the window and pane indexes to their respective IDs 
    # as the indexes of the panes are rearranged after a pane is killed.
    # For example, let's consider that we have these three panes:
    #   Pane ID #1: foo:1.1
    #   Pane ID #2: foo:1.2
    #   Pane ID #3: foo:1.3
    # After killing pane 1, the index of the remaining panes is rearranged so that we will have:
    #   Pane ID #2: foo:1.1
    #   Pane ID #3: foo:1.2
    # The ID is immutable; hence, we have to use it to kill the panes and not the index.
    final_list=""

    # Iterate through each session
    for session_name in $sessions_list; do
        # Retrieve windows for the current session
        session_windows=$(tmux list-windows -F '#{window_index}' -t "$session_name")

        # Iterate through each window in the session to get the list of panes
        for window_idx in $session_windows; do
            to_append=$(tmux list-panes \
                -F "#{session_name}:#{window_index}.#{pane_index}" \
                -t "${session_name}:${window_idx}")
            if [[ -n ${to_append} ]]; then
                final_list+=${to_append}
                final_list+="\n"
            fi
        done
    done

    zoomed=$(tmux display-message -p '#{window_zoomed_flag}')
    if [ "$zoomed" == "0" ]; then
        # zoom the pane when it is not zoomed
        tmux resize-pane -Z
    fi

    # Run FZF with final_list
    selected_items=$(echo -ne "${final_list}" \
        | FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} ${FZF_TMUX_OPTIONS}" fzf-tmux -p65%,80%)

    # Restore pane zoom state if necessary
    if [ "$zoomed" == "0" ]; then
        tmux resize-pane -Z
    fi

    # Handle selected action
    if [[ -n "$selected_items" ]]; then
        key=$(head -1 <<< "$selected_items")
        mapfile -t sessions <<< "$(tail -n+2 <<< "$selected_items")"

        case "$key" in
            ctrl-alt-k)
                to_process=()
                trying_to_kill_curr_pane=false
                for s in "${sessions[@]}"; do
                    # ${s/.*} removes all chars AFTER the first '.' (dot)
                    session_name_and_window_index="${s/.*}"
                    # ${s/*.} removes all chars BEFORE the first '.' (dot)
                    pane_idx="${s/*.}"
                    tmp_val=$(tmux list-panes \
                        -F "#{session_name}:#{window_id}.#{pane_id}" \
                        -f "#{==:#{pane_index},${pane_idx}}" \
                        -t "$session_name_and_window_index")

                    if [ "${tmp_val}" = "${curr_session_window_pane}" ] ; then
                        # skip adding tmp_val to to_process list as it will be appended to the end of the list
                        trying_to_kill_curr_pane=true
                    else
                        to_process+=("$tmp_val")
                    fi
                done
                if [ "${trying_to_kill_curr_pane}" = true ] ; then
                    # killing the current active pane as the last in the list unsures that all panes will be 
                    # correctly killed. 
                    to_process+=("${curr_session_window_pane}")
                fi
                # Kill selected panes
                for to_kill in "${to_process[@]}"; do
                    tmux kill-pane -t "$to_kill"
                done
                ;;
            ctrl-r)
                declare -A to_process
                for s in "${sessions[@]}"; do
                    # ${s/:*} removes all chars AFTER the first ':' (colon)
                    session_name="${s/:*}"
                    # this is a way to remove duplicated values from $sessions array
                    to_process["${session_name}"]=${session_name}
                done
                for to_rename in "${to_process[@]}"; do
                    read -r -p "Rename tmux session '$to_rename' to: " new_session_name
                    tmux rename-session -t "$to_rename" "${new_session_name}"
                done
                ;;
            enter)
                # Switch or attach to the selected session:window_index.pane_index
                [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
                goto_session "${sessions[0]}"
                ;;
        esac
    fi
}

function goto_session() {
    [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
    tmux "${change}" -t "$1"
}

function validate_dir() {
    local base_dir=$1
    local relative_dir=$2

    local target_dir="${base_dir}${relative_dir}"

    if [[ $relative_dir = "~" ]]; then
        target_dir="$base_dir"
    fi

    if [[ -z "${relative_dir}" ]]; then
        # yep... these messages have been generated by AI 😎
        local messages=(
            "Okay, boss! Operation canceled as per your command. 🛑"
            "Your wish is my command. Mission canceled! 🚫"
            "No problem! Operation canceled upon request. 😎"
            "Roger that! Cancelation complete. Over and out! 📞"
            "You got it! Operation canceled just for you. 👍"
            "Alrighty! Task canceled as requested. 😁"
            "Cancelation confirmed! Mission aborted. 👨‍✈️"
            "Done and done! Operation canceled on your orders. 📝"
            "Aye aye, captain! Operation canceled. 🚢"
            "Consider it done! Operation canceled as you asked. 🤝"
        )
        random_message=${messages[RANDOM % ${#messages[@]}]}
        echo "${random_message}"
        exit 1
    fi
    if [[ ! -d "${target_dir}" ]]; then
        echo "Uh-oh, looks like the directory ${target_dir} doesn't exist... that's not supposed to happen. Aborted! 🤷‍♂️"
        exit 1
    fi
}

function create_new_session_and_switch_to() {
    base_dir=$1
    relative_dir=$2
    # echo "creating session for: ${relative_dir}"
    
    # session names can't contain either `.` or `:` so let's replace them with `_`
    session_name="${relative_dir/[.:]/_}-$(date +"%m%d_%H%M%S")"

    # echo "session_name: ${session_name}"

    target_dir=${base_dir}/${relative_dir}
    tmux new-session -s "${session_name}" -d -c "${target_dir}"
    goto_session "${session_name}"
}

arg="$1"

if [ -z "${arg}" ]; then
    arg="-o"
fi

case "${arg}" in
    "-o")
        selected_dir=$(zoxide query -l | sed "s|${HOME}/||" | LC_ALL=C sort -f)
        selected_dir=$(echo -e "~\n${selected_dir}" \
            | FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} ${FZF_TMUX_OPTIONS}" fzf-tmux -p30%,50%)

        validate_dir "${HOME}/" "${selected_dir}"
        create_new_session_and_switch_to "${HOME}/" "${selected_dir}"
        exit 0
        ;;
    "-n")
        selected_dir=$( \
            fd . \
            --type d \
            -H \
            --ignore-file "${HOME}/.gitignore" \
            --exclude .git \
            --base-directory \
            "${HOME}" \
            | LC_ALL=C sort -f)
        selected_dir=$(echo -e "~\n${selected_dir}" \
            | FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} ${FZF_TMUX_OPTIONS}" fzf-tmux -p30%,50%)

        validate_dir "${HOME}/" "${selected_dir}"
        create_new_session_and_switch_to "${HOME}/" "${selected_dir}"
        exit 0
        ;;
    "-t")
        goto_or_kill_session
        exit 0
        ;;
esac

exit 1
